app:
  image: node:4
  volumes:
   - ./app:/app
  links:
   - neo4j
  ports:
   - "3000:3000"
  working_dir: /app
  entrypoint: node server.js

neo4j:
  image: neo4j:3.3
  ports:
   - "7473:7473"
   - "7474:7474"
   - "7687:7687"
  volumes:
   - ./db/dbms:/data/dbms
